# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('model_name', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('price', models.IntegerField()),
                ('mrp', models.IntegerField()),
                ('img_hash', models.CharField(max_length=500)),
                ('brand', models.CharField(max_length=30)),
                ('primart_img', models.IntegerField()),
                ('pcategory', models.CharField(max_length=30)),
                ('scategory', models.CharField(max_length=30)),
                ('features', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
