# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20170601_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='pcategory',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='scategory',
            field=models.CharField(db_index=True, max_length=30),
        ),
    ]
